
package com.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueWS", targetNamespace = "http://service.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueWS {


    /**
     * 
     * @param matricule
     * @return
     *     returns com.service.BanqueEntity
     */
    @WebMethod(operationName = "RecupCompte")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "RecupCompte", targetNamespace = "http://service.com/", className = "com.service.RecupCompte")
    @ResponseWrapper(localName = "RecupCompteResponse", targetNamespace = "http://service.com/", className = "com.service.RecupCompteResponse")
    @Action(input = "http://service.com/BanqueWS/RecupCompteRequest", output = "http://service.com/BanqueWS/RecupCompteResponse")
    public BanqueEntity recupCompte(
        @WebParam(name = "matricule", targetNamespace = "")
        long matricule);

    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConvertionCfatoEuro")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConvertionCfatoEuro", targetNamespace = "http://service.com/", className = "com.service.ConvertionCfatoEuro")
    @ResponseWrapper(localName = "ConvertionCfatoEuroResponse", targetNamespace = "http://service.com/", className = "com.service.ConvertionCfatoEuroResponse")
    @Action(input = "http://service.com/BanqueWS/ConvertionCfatoEuroRequest", output = "http://service.com/BanqueWS/ConvertionCfatoEuroResponse")
    public double convertionCfatoEuro(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @return
     *     returns java.util.List<com.service.BanqueEntity>
     */
    @WebMethod(operationName = "AllCompte")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "AllCompte", targetNamespace = "http://service.com/", className = "com.service.AllCompte")
    @ResponseWrapper(localName = "AllCompteResponse", targetNamespace = "http://service.com/", className = "com.service.AllCompteResponse")
    @Action(input = "http://service.com/BanqueWS/AllCompteRequest", output = "http://service.com/BanqueWS/AllCompteResponse")
    public List<BanqueEntity> allCompte();

}
